export const FETCH_MOVIES_START = 'FETCH_MOVIES_START',
  FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE',
  FETCH_BANNER_MOVIE_START = 'FETCH_BANNER_MOVIE_START',
  FETCH_BANNER_MOVIE_SUCCESS = 'FETCH_BANNER_MOVIE_SUCCESS',
  FETCH_BANNER_MOVIE_FAILURE = 'FETCH_BANNER_MOVIE_FAILURE',
  FETCH_TRAILER_URL_START = 'FETCH_TRAILER_URL_START',
  FETCH_TRAILER_URL_SUCCESS = 'FETCH_TRAILER_URL_SUCCESS';
